"""Closed-world registry.

Every "fact" the semantic checks rely on is defined here and generated by this
system. We are not asserting anything about real merchants or real tax law.
That distinction is the whole reason the semantic channel is defensible: the
reference data is ground truth *inside the simulated world*, not knowledge
recalled from a model.

See docs/SCOPE.md for the external-validity limits this implies.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass(frozen=True)
class Jurisdiction:
    code: str
    name: str
    tax_rate: float  # authoritative inside this world


@dataclass(frozen=True)
class Merchant:
    merchant_id: str
    name: str
    jurisdiction: str
    category: str
    template_id: str          # which layout template this merchant always uses
    address: str
    phone: str


@dataclass
class TransactionRecord:
    """The payment-network side of the story.

    A submitted document claims an amount. The ledger says what was actually
    charged. Disagreement is the single strongest semantic signal in the system
    and it is the one closest to real payments work.
    """
    transaction_id: str
    merchant_id: str
    amount: float
    date: str
    card_last4: str
    auth_code: str


JURISDICTIONS: Dict[str, Jurisdiction] = {
    "NR": Jurisdiction("NR", "Northreach", 0.0625),
    "WD": Jurisdiction("WD", "Westerdale", 0.0875),
    "ES": Jurisdiction("ES", "Eastshore", 0.0450),
    "SM": Jurisdiction("SM", "Southmoor", 0.0000),
}


MERCHANTS: Dict[str, Merchant] = {
    m.merchant_id: m
    for m in [
        Merchant("M001", "Harbourline Supply Co", "NR", "hardware", "T_COMPACT",
                 "418 Quay Street, Northreach", "555-0142"),
        Merchant("M002", "Pinegrove Market", "WD", "grocery", "T_WIDE",
                 "77 Pinegrove Ave, Westerdale", "555-0198"),
        Merchant("M003", "Ashfield Fuel Stop", "ES", "fuel", "T_COMPACT",
                 "1201 Ashfield Rd, Eastshore", "555-0110"),
        Merchant("M004", "Calder & Sons Hardware", "NR", "hardware", "T_WIDE",
                 "9 Calder Lane, Northreach", "555-0177"),
        Merchant("M005", "Bellweather Cafe", "SM", "food", "T_COMPACT",
                 "3 Bellweather Sq, Southmoor", "555-0165"),
        Merchant("M006", "Ridgeway Auto Parts", "WD", "automotive", "T_WIDE",
                 "560 Ridgeway Blvd, Westerdale", "555-0123"),
        Merchant("M007", "Salt Harbor Pharmacy", "ES", "pharmacy", "T_COMPACT",
                 "22 Salt Harbor Way, Eastshore", "555-0189"),
        Merchant("M008", "Thornbury Office Depot", "NR", "office", "T_WIDE",
                 "801 Thornbury St, Northreach", "555-0134"),
    ]
}


CATALOG: Dict[str, List[tuple]] = {
    "hardware": [("Galvanised screws 50pk", 8.40), ("Claw hammer 16oz", 22.95),
                 ("PTFE tape 12mm", 3.15), ("Socket set 24pc", 64.50),
                 ("Wood glue 500ml", 11.20), ("Utility blades 10pk", 6.75)],
    "grocery": [("Whole milk 2L", 3.49), ("Sourdough loaf", 4.95),
                ("Free range eggs 12", 5.60), ("Ground coffee 500g", 12.40),
                ("Olive oil 750ml", 14.85), ("Tinned tomatoes 400g", 1.65)],
    "fuel": [("Unleaded 95 litres", 1.82), ("Screen wash 2L", 7.30),
             ("Engine oil 1L", 15.95), ("Air freshener", 4.20)],
    "food": [("Flat white", 4.10), ("Almond croissant", 4.65),
             ("Chicken sandwich", 9.80), ("Sparkling water", 3.25)],
    "automotive": [("Wiper blade 22in", 18.40), ("Brake fluid DOT4", 12.95),
                   ("Cabin filter", 24.60), ("Bulb H7 pair", 16.80)],
    "pharmacy": [("Ibuprofen 200mg 48pk", 6.90), ("Plasters assorted", 4.35),
                 ("Vitamin D 1000iu", 11.50), ("Antiseptic cream 30g", 7.25)],
    "office": [("A4 paper 500 sheets", 9.90), ("Ballpoint pens 20pk", 7.45),
               ("Lever arch file", 5.80), ("Printer toner black", 78.00),
               ("Sticky notes 6pk", 6.20)],
}


@dataclass
class Ledger:
    """Transaction ledger for the closed world."""
    records: Dict[str, TransactionRecord] = field(default_factory=dict)

    def add(self, rec: TransactionRecord) -> None:
        self.records[rec.transaction_id] = rec

    def get(self, transaction_id: str) -> Optional[TransactionRecord]:
        return self.records.get(transaction_id)

    def __len__(self) -> int:
        return len(self.records)


def tax_rate_for(merchant_id: str) -> float:
    """Authoritative tax rate for a merchant, from the registry."""
    merchant = MERCHANTS[merchant_id]
    return JURISDICTIONS[merchant.jurisdiction].tax_rate


def auth_code(seed: str) -> str:
    return hashlib.sha1(seed.encode()).hexdigest()[:6].upper()
