"""Ledger Forensics dashboard.

Run with:  streamlit run dashboard/app.py
"""

from __future__ import annotations

import json
import sys
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import numpy as np
import pandas as pd
import streamlit as st

from ledger_forensics.decision.policy import AbstentionPolicy
from ledger_forensics.experiments.suite import pick_model, split
from ledger_forensics.forensics import localize
from ledger_forensics.pipeline import SubmissionBuilder, build_dataset
from ledger_forensics.reporting.evidence import build_packet, narrate
from ledger_forensics.tampering.engine import ALL_CLASSES, TamperSpec

st.set_page_config(page_title="Ledger Forensics", layout="wide")
ARTIFACTS = Path(__file__).resolve().parent.parent / "artifacts"


@st.cache_resource(show_spinner="Training the detector, about a minute...")
def load_model(n: int = 160):
    subs = build_dataset(n, seed=7, tamper_rate=0.5)
    train, _, _ = split(subs, frac=0.7, seed=7)
    X = np.array([s.features() for s in train], dtype=np.float32)
    y = np.array([s.label for s in train], dtype=int)
    model = pick_model(train).fit(X, y)
    clean = X[y == 0]
    p_clean = model.predict_proba(clean) if len(clean) else np.array([0.5])
    policy = AbstentionPolicy(float(np.percentile(p_clean, 80)),
                              float(np.percentile(p_clean, 97)))
    return model, policy


@st.cache_data
def load_results():
    path = ARTIFACTS / "results.json"
    return json.loads(path.read_text()) if path.exists() else None


st.title("Ledger Forensics")
st.caption("Multichannel document fraud forensics with error attribution. "
           "All documents are synthetic and generated by this system.")

tab_live, tab_findings, tab_limits = st.tabs(
    ["Inspect a document", "Findings", "What this does not prove"])

# ---------------------------------------------------------------- live
with tab_live:
    col_a, col_b = st.columns([1, 1])
    with col_a:
        choice = st.selectbox("Document to generate",
                              ["none (authentic)"] + ALL_CLASSES)
        go = st.button("Generate and score", type="primary")

    if go:
        model, policy = load_model()
        cls = None if choice.startswith("none") else choice
        builder = SubmissionBuilder(seed=np.random.randint(0, 10_000))
        sub = builder.build(tamper_class=cls,
                            spec=TamperSpec(cls) if cls else None)

        X = sub.features().reshape(1, -1)
        p = float(model.predict_proba(X)[0])
        decision = policy.decide(p)

        with col_a:
            st.image(sub.doc.image, caption=f"{sub.doc.doc_id} "
                     f"(generator {sub.doc.generator_id})", width="stretch")

        with col_b:
            m1, m2, m3 = st.columns(3)
            m1.metric("Risk score", f"{p:.3f}")
            m2.metric("Decision", decision)
            m3.metric("Ground truth",
                      "tampered" if sub.label else "authentic")

            heat = localize.fuse_heatmaps(sub.forensics)
            if heat.max() > 0:
                st.caption("Fused forensic heatmap")
                st.image((heat / (heat.max() + 1e-8)), width="stretch",
                         clamp=True)

            if sub.doc.has_local_mask:
                iou = sub.localisation.get("iou", float("nan"))
                st.caption(f"Localisation IoU against the true edit mask: "
                           f"{iou:.3f}")
            elif sub.label:
                st.caption("This class has no localisable edit region, so "
                           "localisation is undefined rather than a miss.")

            st.subheader("Evidence report")
            packet = build_packet(sub, p, decision)
            st.code(narrate(packet)["text"], language=None)

            st.subheader("Signals")
            st.dataframe(pd.DataFrame({
                "signal": list(sub.forensics.scores),
                "value": [round(float(v), 4)
                          for v in sub.forensics.scores.values()]}),
                hide_index=True, height=240)

# ---------------------------------------------------------------- findings
with tab_findings:
    r = load_results()
    if r is None:
        st.info("No results yet. Run `python run.py demo` to generate them.")
    else:
        st.caption(f"Profile {r['profile']}, {r['runtime_seconds']}s.")

        st.subheader("Does fusion earn its complexity?")
        st.dataframe(pd.DataFrame(r["E1_baseline_ladder"]).T.round(3))

        cm = r.get("E2_channel_matrix", {}).get("share")
        if cm:
            st.subheader("Which channel catches what")
            st.dataframe(pd.DataFrame(
                [{"outcome": k, "share": f"{v:.1%}"} for k, v in cm.items()]),
                hide_index=True)

        pc = r.get("E3_per_class", {}).get("by_class")
        if pc:
            st.subheader("Detection by tamper class")
            st.dataframe(pd.DataFrame(pc).T.round(3))

        at = r.get("E10_attribution", {}).get("primary_cause_share")
        if at:
            st.subheader("Which stage caused the errors")
            st.bar_chart(pd.Series(at))

        for name, cap in [("fig_ladder.png", "Model ladder"),
                          ("fig_per_class.png", "Per class detection"),
                          ("fig_reliability.png", "Calibration"),
                          ("fig_coverage.png", "Review budget"),
                          ("fig_attribution.png", "Error attribution"),
                          ("fig_ocr.png", "OCR error floor")]:
            p = ARTIFACTS / name
            if p.exists():
                st.image(str(p), caption=cap)

# ---------------------------------------------------------------- limits
with tab_limits:
    st.markdown("""
### What this does not prove

**The documents are synthetic.** Every receipt here was generated by this
system, so all results are internal validity only. A detector that works on our
renderer has not been shown to work on real receipts. The unseen-generator
experiment tests part of this and the external-validity harness is the place to
test the rest.

**The OCR is simulated.** The reader returns the values actually rendered on
the image, then injects character errors at a controlled rate. That makes OCR
error a dial the attribution study can sweep, which is why it was done this
way, but no claim about real OCR accuracy follows from it.

**The semantic checks are closed world.** Tax rates, merchant templates and the
transaction ledger are defined by our own registry. Inside the simulation they
are ground truth. They assert nothing about real merchants or real tax law.

**Leave-one-attack-out is narrower than it looks.** Only the fusion layer is
learned. The six forensic detectors and nine semantic checks are deterministic
and see no training data, so holding out an attack tests the combiner's
generalisation, not the system's.

**Prevalence is set, not measured.** The cost analysis resamples to a low fraud
rate because the economics are dominated by base rate. That number is an
assumption and it is stated in the results file.
""")
